sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

env:
  - DOCKER_IMAGE=qinling/minishop
  - TARGET_ENV_ADDR=vm.qinling.io

before_install:
  - openssl aes-256-cbc -K $encrypted_414c18bd42dd_key -iv $encrypted_414c18bd42dd_iv -in ssh.key.enc -out ssh.key -d

install:
  - npm install

script:
  - gulp
  - docker build -t $DOCKER_IMAGE:latest .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:latest
  - docker logout

after_success:

  - ssh -i ssh.key ubuntu@$TARGET_ENV_ADDR docker run 