sudo: required
language: node_js
node_js:
- '6'
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_4da09d2c092c_key -iv $encrypted_4da09d2c092c_iv
  -in deploy/ssh.key.enc -out deploy/ssh.key -d
install:
- npm install
script:
- ng build -prod
- docker build -t $DOCKER_IMAGE - < deploy/Dockerfile
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_IMAGE
- docker logout
after_success:
- scp -q -i ssh.key deploy/deploy.sh ubuntu@$TARGET_ENV_ADDR:/tmp/deploy-minishop.sh
- ssh -i ssh.key ubuntu@$TARGET_ENV_ADDR /bin/bash /tmp/deploy-minishop.sh
notification:
- email:
  - recipients:
    - qinling@live.cn
  - on_failure: always
