sudo: required
language: node_js
node_js:
- '6'
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_4da09d2c092c_key -iv $encrypted_4da09d2c092c_iv
  -in build/ssh.key.enc -out build/ssh.key -d
script:
- cd ui; npm install; ng build -prod; cd ..
- cd service; npm install; gulp; cd ..
- docker build -t $DOCKER_IMAGE -f build/Dockerfile .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_IMAGE
- docker logout
after_success:
- chmod 600 build/ssh.key
- scp -o StrictHostKeyChecking=no -i build/ssh.key build/deploy.sh ubuntu@vm.qinling.io:/tmp/deploy-minishop.sh
- ssh -o StrictHostKeyChecking=no -i build/ssh.key ubuntu@vm.qinling.io /bin/bash /tmp/deploy-minishop.sh
notification:
- email:
  - recipients:
    - qinling@live.cn
  - on_failure: always
