sudo: required
language: node_js
node_js:
- '6'
services:
- docker
env:
- DOCKER_IMAGE="qinling/minishop:latest"
- TARGET_ENV_ADDR="vm.qinling.io"
- REMOTE_SCRIPT="/tmp/deploy-minishop.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_4da09d2c092c_key -iv $encrypted_4da09d2c092c_iv
  -in deploy/ssh.key.enc -out deploy/ssh.key -d
install:
- npm install
script:
- ng build
- docker build -t $DOCKER_IMAGE deploy/
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_IMAGE
- docker logout
after_success:
- scp -q -i ssh.key deploy/deploy.sh ubuntu@$TARGET_ENV_ADDR:$REMOTE_SCRIPT
- ssh -i ssh.key ubuntu@$TARGET_ENV_ADDR /bin/bash $REMOTE_SCRIPT
notification:
- email:
  - recipients:
    - qinling@live.cn
  - on_failure: always
